baseURL = 'https://z0ing.github.io/'
locale = 'zh-cn'
title = "Zou'Log"
theme = "PaperMod"

paginate = 10                                 # 首页每页显示文章数
enableRobotsTXT = true                        # 允许搜索引擎抓取

[params]

  description = "Hi, this is ZouMing. I’m documenting my learning notes in this blog"          # 这个只给搜索引擎和社交卡片用，不会显示在页面上
    # --- 文章页面 ---
  ShowReadingTime = true                      # 显示预计阅读时间
  ShowPostNavLinks = true                     # 显示上一篇/下一篇导航
  ShowBreadCrumbs = true                      # 显示面包屑导航
  ShowCodeCopyButtons = true                  # 代码块显示复制按钮
  ShowToc = true                              # 显示文章目录(TOC)
  TocOpen = false                             # 目录默认折叠(true=展开)

[params.homeInfoParams]
    # --- 首页展示 ---
  Title = "Welcome to Zou'Log"
  # 通过 HTML 手动控制间距、添加按钮或图标
  Content = """
    <p style="margin-bottom:0.5rem;">I'm documenting my learning notes in this blog</p>
    <a href="/posts/" style="font-size:0.9rem;">→ Browse all posts</a>
  """



[[menu.main]]
  identifier = "posts"
  name = "Logs"
  url = "/posts/"
  weight = 5

[[menu.main]]
  identifier = "archives"
  name = "Archives"
  url = "/archives/"
  weight = 10

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 15

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 20